/**
 * The media bin's compose panel: ask Higgsfield for a photo.
 *
 * It sits *inside* the bin rather than over it, because the bin is the reference picker —
 * while this is open every usable photo tile is a toggle, and covering them would defeat
 * the whole flow. Two controls carry the default path (type, press Generate); the model
 * and the aspect ratio live behind a disclosure, because a photo that matches the
 * project's own frame is what almost every generation wants.
 */

import { useState } from 'react';
import * as backend from '../lib/backend';
import { useEditor } from '../state/store';

export function ImageCompose() {
  const panel = useEditor((s) => s.imagePanel);
  const settings = useEditor((s) => s.settings);
  const setImagePrompt = useEditor((s) => s.setImagePrompt);
  const setImageModel = useEditor((s) => s.setImageModel);
  const setImageAspect = useEditor((s) => s.setImageAspect);
  const closeImagePanel = useEditor((s) => s.closeImagePanel);
  const startImageGeneration = useEditor((s) => s.startImageGeneration);
  const openSettings = useEditor((s) => s.openSettings);

  const [showOptions, setShowOptions] = useState(false);

  if (!panel.open) return null;

  const connected = Boolean(settings?.configured);
  const attached = panel.referenceAssetIds.length;
  const limit = backend.imageReferenceLimit(panel.modelId);

  return (
    // Not a dialog: it is part of the bin, and the editor behind it stays live.
    <div className="compose" role="group" aria-label="Generate an image">
      <label className="visually-hidden" htmlFor="image-prompt">
        Describe the image to generate
      </label>
      <textarea
        id="image-prompt"
        className="prompt"
        autoFocus
        placeholder="Describe the image…"
        value={panel.prompt}
        onChange={(e) => setImagePrompt(e.target.value)}
      />

      <p className="hint">
        {attached === 0
          ? 'Click photos below to generate on top of them.'
          : `${attached} of ${limit} references — click a photo to add or remove it.`}
      </p>

      <button
        type="button"
        className="linklike"
        aria-expanded={showOptions}
        onClick={() => setShowOptions(!showOptions)}
      >
        {showOptions ? 'Hide options' : 'Options'}
      </button>

      {showOptions && (
        <>
          {/* Labelled "Image model" rather than "Model": the transition picker of that
              name can be on screen at the same time, in the inspector. */}
          <div className="field">
            <label htmlFor="image-model">Image model</label>
            <select
              id="image-model"
              value={panel.modelId}
              onChange={(e) => setImageModel(e.target.value)}
            >
              {backend.IMAGE_MODELS.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.label}
                </option>
              ))}
            </select>
          </div>
          <div className="field">
            <label htmlFor="image-aspect">Aspect ratio</label>
            <select
              id="image-aspect"
              value={panel.aspect}
              onChange={(e) => setImageAspect(e.target.value)}
            >
              {backend.imageAspects(panel.modelId).map((aspect) => (
                <option key={aspect} value={aspect}>
                  {aspect}
                </option>
              ))}
            </select>
          </div>
        </>
      )}

      {!connected && (
        <div className="callout" role="status">
          <b>Connect Higgsfield to generate</b>
          {backend.isDesktop()
            ? 'Photos are generated by Higgsfield — there is no local generator to fall back on. Nothing has been sent.'
            : 'Generating needs the SolCut desktop app — run it with `pnpm tauri dev`. Nothing has been sent.'}
          <button type="button" onClick={openSettings}>
            Open settings →
          </button>
        </div>
      )}

      <button
        type="button"
        className="block-btn"
        disabled={!connected || panel.prompt.trim() === ''}
        onClick={() => startImageGeneration()}
      >
        ✦ Generate image
      </button>
      {/* Named for what it closes: a bare "Cancel" would answer to the same query as the
          settings dialog's, and the two mean different things. */}
      <button
        type="button"
        className="linklike"
        aria-label="Close the generate panel"
        onClick={closeImagePanel}
      >
        Cancel
      </button>
    </div>
  );
}
